# Generated by Django 2.0.13 on 2019-06-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0003_remove_result_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='course',
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='result',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teacher.Subject'),
        ),
    ]
