# Generated by Django 2.0.13 on 2019-06-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190618_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='rt1_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='result',
            name='rt2_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='result',
            name='sa1_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='result',
            name='sa2_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='result',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
